#!/bin/bash

usage() {
    echo "usage: $(basename "${0}") <audio-file> <start-time> [<end-time>]"
    exit 1
}

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
    usage
fi

audio_file="${1}"
start_time="${2}"

if [ $# -eq 3 ]; then
    end_time="${3}"
else
    end_time="$(ffmpeg -i "${audio_file}" 2>&1 | grep "Duration" | awk '{gsub(",", "", $2); print $2}')"
fi

# validate times
if ! [[ "${start_time}" =~ ^[0-9]+:[0-9]+:[0-9]+(\.[0-9]+)?$ ]]; then
    echo "Error: Invalid start time format: ${start_time}"
    exit 1
elif ! [[ "${end_time}" =~ ^[0-9]+:[0-9]+:[0-9]+(\.[0-9]+)?$ ]]; then
    echo "Error: Invalid end time format: ${end_time}"
    exit 1
fi

file_extension="${audio_file##*.}"
output="${audio_file}_trimmed.${file_extension}"

ffmpeg -y -v quiet -hide_banner -i "${audio_file}" -ss "${start_time}" -to "${end_time}" -vn -acodec libmp3lame -ac 2 -ab 160k -ar 48000 "${output}"
echo "${output}"
