#!/bin/bash

usage() {
    echo "Usage: $(basename "${0}") [--list-settings] [--list-keys <setting>] set <setting> <value> | get <setting> | increase <setting> | decrease <setting> | reset <setting> | preset list|apply|store <name>" 1>&2
    exit 1
}

clean_preset_name() {
    local name="${1}"
    echo "${name}" | sed -E 's|[^a-zA-Z0-9]|_|g'
}

clean_preset() {
    local preset_file="${1}"
    if cat "${preset_file}" | grep -q "^white_balance_automatic=1$"; then
        # delete white_balance_temperature values
        sed -i -E '/^white_balance_temperature=.+$/d' "${preset_file}"
        echo "Deleted white_balance_temperature setting, since white_balance_automatic is set to 1"
    fi
    if cat "${preset_file}" | grep -q "^auto_exposure=[2-3]$"; then
        sed -i -E '/^exposure_time_absolute=.+$/d' "${preset_file}"
        echo "Deleted exposure_time_absolute setting, since auto_exposure is set to 2 or 3"
    fi
    if cat "${preset_file}" | grep -q "^privacy=[0-1]$"; then
        sed -i -E '/^privacy=.+$/d' "${preset_file}"
        echo "Deleted privacy setting, since it cannot be set"
    fi
}

PRESET_FOLDER="${HOME}/.config/cam-settings"

raw=0
mode=""
setting=""
setting_value=""
preset_mode=""
preset_name=""

while [ $# -gt 0 ]; do
    case "${1}" in
        --list-settings)
            mode="list-settings"
            ;;
        --list-keys)
            mode="list-keys"
            shift
            setting="${1}"
            [ -z "${setting}" ] && usage
            ;;
        set)
            mode="set"
            shift
            setting="${1}"
            shift
            setting_value="${1}"
            [ -z "${setting}" ] && usage 
            [ -z "${setting_value}" ] && usage
            ;;
        get)
            mode="get"
            shift
            option_or_setting="${1}"
            if [[ "${option_or_setting}" == "-r" || "${option_or_setting}" == "--raw" ]]; then
                raw=1
                shift
                option_or_setting="${1}"
            fi
            [ -z "${option_or_setting}" ] && usage
            setting="${option_or_setting}"
            ;;
        increase)
            mode="increase"
            shift
            setting="${1}"
            if [ -z "${setting}" ]; then
                usage
            fi
            ;;
        decrease)
            mode="decrease"
            shift
            setting="${1}"
            if [ -z "${setting}" ]; then
                usage
            fi
            ;;
        reset)
            mode="reset"
            shift
            setting="${1}"
            if [ -z "${setting}" ]; then
                usage
            fi
            ;;
        preset)
            mode="preset"
            shift
            if [ "${1}" = "apply" ]; then
                preset_mode="apply"
            elif [ "${1}" = "store" ]; then
                preset_mode="store"
            elif [ "${1}" = "show" ]; then
                preset_mode="show"
            elif [ "${1}" = "list" ]; then
                preset_mode="list"
            else
                usage
            fi
            if [ "${preset_mode}" != "list" ]; then
                shift
                preset_name=$(clean_preset_name "${1}")
                if [ -z "${preset_name}" ]; then
                    usage
                fi
            fi
            ;;
            
        *)
            usage
            ;;
    esac
    shift
done

if [ -z "${mode}" ]; then
    usage
fi

settings="$(v4l2-ctl -l | grep '0x' | sed -E 's|\s+| |g ; s|^\s|| ; s|\s$|| ; s|0x[0-9a-z]+\s\([^)]+\)\s+:\s+|| ; s|\(([^)]+)\)$|info=\1| ; s|\s([a-z]+=)|\t\1|g')"
if [ -z "${settings}" ]; then
    echo "ERROR: v4l2-ctl failed" 1>&2
    exit 1
fi

case "${mode}" in
    set)
        v4l2-ctl -c "${setting}=${setting_value}"
        exit_code=$?
        [ ${exit_code} -eq 0 ] && echo "Set $(v4l2-ctl -C "${setting}")"
        exit ${exit_code}
        ;;
    get)
        value="$(v4l2-ctl -C "${setting}")"
        exit_code=$?
        if [ ${exit_code} -eq 0 ] && [ ${raw} -eq 1 ]; then
            echo "${value}" | sed -E 's/^'"${setting}"': //'
        else
            echo "${value}"
        fi
        exit ${exit_code}
        ;;
    preset)
        preset_file="${PRESET_FOLDER}/${preset_name}.preset"
        case "${preset_mode}" in
            apply)
                [ ! -f "${preset_file}" ] && echo "ERROR: Preset ${preset_name} not found" 1>&2 && exit 1
                cat "${preset_file}" | while IFS= read -r line; do
                    setting="${line%=*}"
                    if v4l2-ctl -c "${line}"; then
                        echo "Set $(v4l2-ctl -C "${setting}")"
                    else
                        echo "ERROR: Failed to apply '${line}' from preset '${preset_name}'" 1>&2
                        exit 1
                    fi
                done
                echo "Applied preset '${preset_name}'"
                exit 0
                ;;
            store)
                [ ! -d "${PRESET_FOLDER}" ] && mkdir -p "${PRESET_FOLDER}"
                >"${preset_file}"
                exit_code=0
                while IFS=$'\t' read -r key remainder; do
                    v4l2-ctl -C "${key}" | sed -E 's/^'"${key}"': ([0-9]+).*$/\1/' | sed -E 's/^/'"${key}"='/g' | tee --append "${preset_file}"
                done < <(echo "${settings}")
                echo
                if [ ${exit_code} -eq 0 ]; then
                    clean_preset "${preset_file}"
                    echo "Stored preset '${preset_name}'"
                fi
                exit 0 
                ;;
            show)
                [ ! -f "${preset_file}" ] && echo "ERROR: Preset ${preset_name} not found" 1>&2 && exit 1
                cat "${preset_file}"
                exit 0
                ;;
            list)
                ls -1 "${PRESET_FOLDER}" 2>/dev/null | sed 's/\.preset$//'
                exit 0
                ;;
        esac
        ;;
esac

while IFS=$'\t' read -r key prop1 prop2 prop3 prop4 prop5 prop6 prop7 prop8 prop9 prop10; do
    props=( "${prop1}" "${prop2}" "${prop3}" "${prop4}" "${prop5}" "${prop6}" "${prop7}" "${prop8}" "${prop9}" "${prop10}" )
    case "${mode}" in
        list-settings)
            echo "${key}"
            ;;
        list-keys)
            if [ "${setting}" = "${key}" ]; then
                for prop in "${props[@]}"; do
                    if [ -n "${prop}" ]; then
                        prop_key="${prop%=*}"
                        prop_value="${prop#*=}"
                        echo "${prop_key}: ${prop_value}"
                    fi
                done
                exit 0
            fi
            ;;
        increase|decrease|reset)
            if [ "${setting}" = "${key}" ]; then
                min=0
                max=0
                step=1
                value=0
                default=0
                for prop in "${props[@]}"; do
                    if [ -n "${prop}" ]; then
                        prop_key="${prop%=*}"
                        case "${prop_key}" in
                            min)
                                min="${prop#*=}"
                                ;;
                            max)
                                max="${prop#*=}"
                                ;;
                            step)
                                step="${prop#*=}"
                                ;;
                            value)
                                value="${prop#*=}"
                                ;;
                            default)
                                default="${prop#*=}"
                                ;;
                        esac
                    fi
                done
                value=${value:-${default}}
                step=${step:-1}
                if [ "${mode}" = "increase" ]; then
                    value=$((value + step))
                    [ ${value} -gt ${max} ] && value=${max}
                elif [ "${mode}" = "decrease" ]; then
                    value=$((value - step))
                    [ ${value} -lt ${min} ] && value=${min}
                elif [ "${mode}" = "reset" ]; then
                    value=${default}
                fi
                v4l2-ctl -c "${setting}=${value}"
                exit_code=$?
                [ ${exit_code} -eq 0 ] && echo "Set $(v4l2-ctl -C "${setting}")"
                exit ${exit_code}
            fi
            ;;
    esac
done < <(echo "${settings}")

exit 1
