#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: "$(basename ${0})" <file|command>"
    exit 1
fi

if [ "${1:0:1}" = "/" ] || [ "${1:0:2}" = "./" ]; then
    file="${1}"
else
    file="$(which ${1})"
    if [ -z "${file}" ]; then
        file="/usr/local/bin/${1}"
    fi
fi

if [ ! -f "${file}" ]; then
    echo "ERROR: File not found: ${file}" 1>&2
    exit 1
fi

cat "${file}"
