#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
. "${SCRIPT_DIR}/lib-desktop"


usage() {
    echo "usage: $(basename "${0}") [--jpg]" 1>&2
    exit 1
}

error() {
    echo "ERROR: ${1}" 1>&2
}

fail() {
    error "${1}"
    exit 1
}

jpg=0
while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            ;;
        --jpg)
            jpg=1
            ;;
        *)
            usage
            ;;
    esac
    shift
done

tmpfile=""
ext=""
if cli_helpers_is_wayland; then
    cli_helpers_require_command wl-paste wl-clipboard || exit 1
    image_mime_type="$(wl-paste --list-types | egrep -m 1 '^image/')"
else
    image_mime_type="$(xclip -selection clipboard -t TARGETS -o | egrep -m 1 '^image/')"
fi
if [ -z "${image_mime_type}" ]; then
    # no image in clipboard, try downloading if it is a URL
    if cli_helpers_is_wayland; then
        text="$(wl-paste 2>/dev/null)"
    else
        text="$(DISPLAY=$(xdisplay) xclip -o -sel c)"
    fi
    if [[ "${text}" =~ ^https?:// ]]; then
        tmpfile=$(mktemp "/tmp/clip-paste-image.XXXXXX")
        if ! curl -sS -L -o "${tmpfile}" "${text}"; then
            rm -f "${tmpfile}" 2> /dev/null
            fail "Failed to download ${text}"
        fi
        image_mime_type="$(mimetype --output-format %m "${tmpfile}" 2> /dev/null)"
    fi
else
    tmpfile=$(mktemp "/tmp/clip-paste-image.XXXXXX")
    if cli_helpers_is_wayland; then
        wl-paste --type "${image_mime_type}" > "${tmpfile}"
    else
        xclip -selection clipboard -t "${image_mime_type}" -o > "${tmpfile}"
    fi
fi

if [ -z "${image_mime_type}" ]; then
    # nothing usable found
    [ -n "${tmpfile}" ] && rm -f "${tmpfile}" 2> /dev/null
    fail "No image found in clipboard"
    exit 1
fi

ext=$(mime-to-ext "${image_mime_type}" 2> /dev/null)
[ -n "${ext}" ] && mv "${tmpfile}" "${tmpfile}.${ext}" && tmpfile="${tmpfile}.${ext}"

if [ ${jpg} -eq 1 ]; then
    ext="jpg"
    convert "${tmpfile}" "${tmpfile}.${ext}"
    rm -f "${tmpfile}" 2> /dev/null
    tmpfile="${tmpfile}.${ext}"
fi

echo "${tmpfile}"
