#!/bin/bash

usage() {
    echo "usage: $(basename "${0}") [-c|--clipboard|-p|--primary]" 1>&2
    exit 1
}

clipboard="clipboard"
while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            ;;
        -p|--primary)
            clipboard="primary"
            shift
            ;;
        -c|--clipboard)
            clipboard="clipboard"
            shift
            ;;
        *)
            usage
            ;;
    esac
done

echo | DISPLAY=$(xdisplay) xclip -r -selection "${clipboard}"
