#!/bin/bash

declare -A overwrites
overwrites["audio/mpeg"]="mp3"

usage()
{
    echo "Usage: $(basename "${0}") <file>" 1>&2
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

ext=""
mime_type="$(file --mime-type -b "${1}")"

if [ -n "${mime_type}" ]; then
    ext="${overwrites["${mime_type}"]}"
    if [ -z "${ext}" ]; then
        exts="$(grep -wF -m 1 "${mime_type}" "/etc/mime.types" | sed 's/^[^\t]\{1,\}\t\{1,\}\(.\{1,\}\)$/\1/')"
        ext="$(echo "${exts}" | cut -d ' ' -f 1)"
    fi
fi

[ -z "${ext}" ] && exit 1
echo "${ext}"
exit 0
