#!/bin/bash

APP_NAME="$(basename "${0}")"

usage() {
    cat <<EOF 1>&2
usage: ${APP_NAME} [OPTIONS]

Generate a random password.

Options:
  -h, --help            Print this help message.
  -l, --length LENGTH   The length of the password to generate, default: 12
EOF
    exit 1
}

error() {
    echo "ERROR: ${1}" 1>&2
}

fail() {
    error "${1}"
    exit 1
}

check_command() {
    local cmd="${1}"; shift
    command -v "${cmd}" >/dev/null 2>&1 || fail "${cmd} is not installed"
}

length=12

while [ "${1}" != "" ]; do
    case "${1}" in
        -h | --help)
            usage
            ;;
        -l|--length)
            shift
            [ -z "${1}" ] && error "length must not be empty" && usage
            [[ ! "${1}" =~ ^[0-9]+$ ]] && fail "length must be a number"
            [[ "${1}" -le 0 ]] && fail "length must be greater than 0"
            length="${1}"
            ;;
        *)
            usage
            ;;
    esac
    shift
done

check_command openssl
check_command tr

openssl rand -base64 "${length}" | tr -d '\n'
exit 0
