#!/bin/bash

usage() {
    echo "usage: $(basename "${0}") [-h|--help] [-f|--file <file>] [-t|--with-timestamp]" 1>&2
    echo
    echo "Write data from stdin to history file."
    echo
    echo "Options:"
    echo "  -h, --help:                print this help message" 1>&2
    echo "  -f <file>, --file <file>:  history file, defaults to \$HISTFILE or ~/.bash_history" 1>&2
    echo "  -t, --with-timestamp:      include timestamp in history, defaults to whether \$HISTTIMEFORMAT is set" 1>&2
    echo
    exit 1
}

while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            ;;
        -f|--file)
            shift
            [ -z "${1}" ] && usage
            HISTFILE="${1}"
            ;;
        -t|--with-timestamp)
            HISTTIMEFORMAT="whatever"
            ;;
        *)
            usage
            ;;
    esac
    shift
done

if [ -n "${HISTFILE}" ]; then
    # write to history immediately
    default_history_file=~/.bash_history
    current_history_file="${HISTFILE}"
    if [ -z "${current_history_file}" ]; then
        current_history_file="${default_history_file}"
    fi
    nl=$'\n'
    line=""
    if [ -n "${HISTTIMEFORMAT}" ]; then
        line="#$(date +%s)${nl}"
    fi
    line="${line}$(cat -)"
    echo "${line}" >> "${current_history_file}"
fi
