#!/usr/bin/env python3

import argparse
import base64


def encode_image(image_path):
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode('utf-8')

def main():
    parser = argparse.ArgumentParser(description='Convert image files to base64 URLs', formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('file', type=str, help='Path to image file')

    args = parser.parse_args()
    image_path = args.file

    base64_image = encode_image(image_path)
    print(f"data:image/jpeg;base64,{base64_image}")

if __name__ == "__main__":
    main()
