#!/bin/bash

usage() {
    echo "Usage: $(basename "${0}") <files or - for stdin>"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

if [ "${1}" = "-" ]; then
    files=$(cat)
else
    files="${@}"
fi

if [ -t 0 ]; then
    echo "(Press h for help)"
fi

for f in ${files}; do
    if [ ! -f "${f}" ]; then
        echo "ERROR: file not found: ${f}" 1>&2
        continue
    fi
    mpg123 -q "${f}"
done
