#!/bin/bash

APP_NAME="$(basename "${0}")"

# create a dictionary of names and SSIDs for easy lookup
# this is not the best way to do this but it works
declare -A names_to_ssids
names_to_ssids["mobile"]="Punkt"
names_to_ssids["work"]="Mittwald"
names_to_ssids["home"]="Dave"

names="${!names_to_ssids[@]}"
ssid=$(iwgetid -r)
force=0


usage() {
    cat <<EOF 1>&2
usage: ${APP_NAME} [OPTIONS] NAME

Manage wifi connections

  NAME                      Name of wifi connection
                            One of: $(echo "${names} auto" | sed 's/ /, /g')

Options:
  -h, --help                show this help message
  -m, --map SSID            map SSID to NAME
  -r, --reconnect           force reconnect
  -k, --reload-module       reload kernel module
  -d, --disconnect          disconnect
  -f, --force               force reconnect
  --list-available-ssids    list available SSIDs
  --list-available-names    list available names
  --print-names             print possible names
EOF
    exit 1
}

error() {
    echo "ERROR: ${1}" 1>&2
}

fail() {
    error "${1}"
    exit 1
}

map_ssid_to_name() {
    local ssid="${1}"
    for name in ${names}; do
        mapped="${names_to_ssids[${name}]}"
        mapfile -t mapped <<< "${mapped//|/$'\n'}"
        for mapped_ssid in "${mapped[@]}"; do
            if [ "${ssid}" == "${mapped_ssid}" ]; then
                echo "${name}"
                return 0
            fi
        done
    done
    return 1
}

list_available_ssids() {
    local raw_list
    for i in $(seq 1 3); do
        raw_list="$(nmcli --terse dev wifi list)"
        [ -n "${raw_list}" ] && break
        sleep 2
    done
    echo "${raw_list}" | sed -E 's/^[ *]:([A-Z0-9]{2}\\:){5}[A-Z0-9]{2}:([^:]+):.+$/\2/g' | sort -u
}

map_available_ssids_to_names() {
    local available_ssids=$(list_available_ssids)
    for ssid in ${available_ssids}; do
        map_ssid_to_name "${ssid}"
    done
    return 0
}

reload_kernel_module() {
    local module=""
    module="$(lspci -k 2>/dev/null | grep -A3 -i 'network' | grep -i 'kernel modules' | sed -E 's/^.+:\s*(.+)$/\1/')"
    [ -z "${module}" ] && fail "Failed to find networking kernel module"
    sudo modprobe -r "${module}" || fail "Failed unload kernel module ${module}"
    sudo modprobe "${module}" || fail "Failed to reload kernel module ${module}"
    return 0
}

# no arg, show current wifi (mapped)
if [ "${#}" -lt 1 ]; then
    if [ -n "${ssid}" ]; then
        map_ssid_to_name "${ssid}" || echo "${ssid}"
    else
        fail "Not connected to wifi"
    fi
    exit 0
fi

name_to_connect=""

while [ "${#}" -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            ;;
        -m|--map)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -z "${1}" ] && usage
            ssid="${1}"
            shift; [ -n "${1}" ] && usage
            map_ssid_to_name "${ssid}" && exit 0
            fail "Unknown SSID: ${ssid}"
            ;;
        -r|--reconnect)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -n "${1}" ] && usage
            nmcli radio wifi off
            sleep 1
            nmcli radio wifi on
            sleep 2
            [ -n "${ssid}" ] && nmcli c up "${ssid}"
            exit 0
            ;;
        -k|--reload-module)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -n "${1}" ] && usage
            reload_kernel_module
            exit 0
            ;;
        -d|--disconnect)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -n "${1}" ] && usage
            nmcli radio wifi off
            sleep 1
            nmcli radio wifi on
            sleep 2
            exit 0
            ;;
        --list-available-ssids)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -n "${1}" ] && usage
            list_available_ssids
            exit 0
            ;;
        --list-available-names)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -n "${1}" ] && usage
            map_available_ssids_to_names
            exit 0
            ;;
        -f|--force)
            force=1
            ;;
        --print-names)
            [ -n "${name_to_connect}" ] && usage
            shift; [ -n "${1}" ] && usage
            echo "${names} auto"
            exit 0
            ;;
        auto)
            available_names="$(map_available_ssids_to_names)"
            if echo "${available_names}" | grep -q "work"; then
                name_to_connect="work"
            elif echo "${available_names}" | grep -q "home"; then
                name_to_connect="home"
            else
                name_to_connect="mobile"
            fi
            ;;
        *)
            if [ -z "${name_to_connect}" ]; then
                name_to_connect="${1}"
            else
                usage
            fi
            ;;
    esac
    shift
done

for name in ${names}; do
    if [ "${name}" == "${name_to_connect}" ]; then
        mapped_ssids="${names_to_ssids[${name}]}"
        mapfile -t mapped_ssids <<< "${mapped_ssids//|/$'\n'}"

        up=0
        found=0
        for s in "${mapped_ssids[@]}"; do
            if [ "${s}" == "${ssid}" ]; then
                found=1
                break
            fi
        done

        if [ "${found}" -eq 0 ]; then
            # connected to a different SSID
            up=1
        elif [ "${force}" -eq 1 ]; then
            # force reconnect
            up=1
        elif ! ping -c 1 -W 1 google.de &>/dev/null; then
            # connected but no internet
            up=1
        fi
        if [ "${up}" -eq 1 ]; then
            last_exit=1
            for s in "${mapped_ssids[@]}"; do
                nmcli c up "${s}"
                last_exit=$?
                if [ "${last_exit}" -eq 0 ]; then
                    # success
                    break
                fi
            done
            exit ${last_exit}
        fi
        exit 0
    fi
done

usage
