#!/bin/bash

usage() {
    echo "Usage: $(basename "${0}") <desktop> <classes ...> -- [<arguments...>]"
    exit 1
}

set -x

desktop_file=""
classes=""


while [ "$#" -gt 0 ]; do
    case "$1" in
        --)
            shift
            break
            ;;
        *)
            if [ -z "${desktop_file}" ]; then
                desktop_file="${1}"
            else
                [ -n "${classes}" ] && classes="${classes} "
                classes="${classes}${1}"
            fi
            ;;
    esac
    shift
done

[ -z "${desktop_file}" ] && usage
[ -z "${classes}" ] && usage

window-focus-by-class ${classes} || gtk-launch "${desktop_file}" ${@} &> /dev/null
