#!/bin/bash

usage() {
    echo "Usage: $(basename "${0}") [--wait <seconds>] <classes ...>"
    exit 1
}

wait_seconds=0
classes=""

while [ "$#" -gt 0 ]; do
    case "${1}" in
        --wait)
            shift
            [[ "${1}" =~ ^[0-9]+$ ]] || usage
            wait_seconds="${1}"
            ;;
        *)
            [ -n "${classes}" ] && classes="${classes} "
            classes="${classes}${1}"
            ;;
    esac
    shift
done

# get all windows by class name
windows=""
while true; do
    windows="$(window-by-class ${classes})"
    [ -n "${windows}" ] && break
    if [ "${wait_seconds}" -gt 0 ]; then
        sleep 1
        ((wait_seconds--))
    else
        exit 1
    fi
done
active=$(window-active)
echo "Active window: ${active}"
if [ -z "${active}" ]; then
    # no active window, use the first one
    window-focus $(echo "${windows}" | head -n 1)
else
    next=$(echo "${windows}" | grep -A 1 "${active}" | grep -v "${active}" | tail -n 1)
    if [ -z "${next}" ]; then
        next=$(echo "${windows}" | head -n 1)
    fi
    echo "Next window: ${next}"
    window-focus "${next}"
fi
